export const userData = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    email: 'john@example.com',
    phoneNo: '123-456-7890',
    dob: '1990-05-15',
    gender: 'Male',
    address: [
      {
        id: 1,
        streetAddress: '123 Main St',
        city: 'Anytown',
        state: 'CA',
        postalCode: '12345',
        country: 'USA',
      },
      {
        id: 2,
        streetAddress: '789 Pine Ave',
        city: 'Anytown',
        state: 'NY',
        postalCode: '24680',
        country: 'USA',
      },
      {
        id: 3,
        streetAddress: '123 Oak St',
        city: 'Nowhere',
        state: 'CA',
        postalCode: '54321',
        country: 'USA',
      },
      {
        id: 4,
        streetAddress: '789 Cedar Ave',
        city: 'Anywhere',
        state: 'TX',
        postalCode: '45678',
        country: 'USA',
      },
    ],
  },
  {
    id: 2,
    firstName: 'Alice',
    lastName: 'Smith',
    email: 'alice@example.com',
    phoneNo: '987-654-3210',
    dob: '1985-10-20',
    gender: 'Female',
    address: [
      {
        id: 1,
        streetAddress: '456 Oak Ave',
        city: 'Sometown',
        state: 'NY',
        postalCode: '54321',
        country: 'USA',
      },
    ],
  },
  {
    id: 3,
    firstName: 'Michael',
    lastName: 'Johnson',
    email: 'michael@example.com',
    phoneNo: '555-555-5555',
    dob: '1978-03-25',
    gender: 'Male',
    address: [
      {
        id: 1,
        streetAddress: '789 Elm St',
        city: 'Othertown',
        state: 'TX',
        postalCode: '67890',
        country: 'USA',
      },
    ],
  },
  {
    id: 4,
    firstName: 'Emily',
    lastName: 'Brown',
    email: 'emily@example.com',
    phoneNo: '111-222-3333',
    dob: '1995-12-10',
    gender: 'Female',
    address: [
      {
        id: 1,
        streetAddress: '321 Pine St',
        city: 'Anothertown',
        state: 'FL',
        postalCode: '13579',
        country: 'USA',
      },
    ],
  },
  {
    id: 5,
    firstName: 'James',
    lastName: 'Taylor',
    email: 'james@example.com',
    phoneNo: '444-555-6666',
    dob: '1982-08-05',
    gender: 'Male',
    address: [
      {
        id: 1,
        streetAddress: '654 Maple Ave',
        city: 'Somewhere',
        state: 'WA',
        postalCode: '24680',
        country: 'USA',
      },
    ],
  },
  {
    id: 6,
    firstName: 'Sarah',
    lastName: 'Wilson',
    email: 'sarah@example.com',
    phoneNo: '777-888-9999',
    dob: '1998-04-30',
    gender: 'Female',
    address: [
      {
        id: 1,
        streetAddress: '987 Birch St',
        city: 'Nowhere',
        state: 'CA',
        postalCode: '97531',
        country: 'USA',
      },
    ],
  },
  {
    id: 7,
    firstName: 'David',
    lastName: 'Martinez',
    email: 'david@example.com',
    phoneNo: '999-999-9999',
    dob: '1980-11-15',
    gender: 'Male',
    address: [
      {
        id: 1,
        streetAddress: '789 Cedar Ave',
        city: 'Anywhere',
        state: 'TX',
        postalCode: '45678',
        country: 'USA',
      },
    ],
  },
  {
    id: 8,
    firstName: 'Jessica',
    lastName: 'Garcia',
    email: 'jessica@example.com',
    phoneNo: '123-123-1234',
    dob: '1992-07-20',
    gender: 'Female',
    address: [
      {
        id: 1,
        streetAddress: '456 Walnut St',
        city: 'Everywhere',
        state: 'FL',
        postalCode: '98765',
        country: 'USA',
      },
    ],
  },
  {
    id: 9,
    firstName: 'Daniel',
    lastName: 'Lopez',
    email: 'daniel@example.com',
    phoneNo: '987-987-9876',
    dob: '1987-02-28',
    gender: 'Male',
    address: [
      {
        id: 1,
        streetAddress: '123 Oak St',
        city: 'Nowhere',
        state: 'CA',
        postalCode: '54321',
        country: 'USA',
      },
    ],
  },
  {
    id: 10,
    firstName: 'Michelle',
    lastName: 'Rodriguez',
    email: 'michelle@example.com',
    phoneNo: '555-123-4567',
    dob: '1993-09-05',
    gender: 'Female',
    address: [
      {
        id: 1,
        streetAddress: '789 Pine Ave',
        city: 'Anytown',
        state: 'NY',
        postalCode: '24680',
        country: 'USA',
      },
    ],
  },
]

export const singleUser = {
  id: 1,
  firstName: 'John',
  lastName: 'Doe',
  email: 'john@example.com',
  phoneNo: '123-456-7890',
  dob: '1990-05-15',
  gender: 'Male',
  address: [
    {
      id: 1,
      streetAddress: '123 Main St',
      city: 'Anytown',
      state: 'CA',
      postalCode: '12345',
      country: 'USA',
    },
    {
      id: 2,
      streetAddress: '789 Pine Ave',
      city: 'Anytown',
      state: 'NY',
      postalCode: '24680',
      country: 'USA',
    },
    {
      id: 3,
      streetAddress: '123 Oak St',
      city: 'Nowhere',
      state: 'CA',
      postalCode: '54321',
      country: 'USA',
    },
    {
      id: 4,
      streetAddress: '789 Cedar Ave',
      city: 'Anywhere',
      state: 'TX',
      postalCode: '45678',
      country: 'USA',
    },
  ],
}
